---
#title: \sffamily \textcolor{teal}{Michael Long, PhD Candidate}
#subtitle: _\textsf{\textcolor{teal}{Cognitive Psychologist}}_
fontsize: 12pt
output:
  pdf_document:
    extra_dependencies: ['amsmath','setspace']
---
\sffamily
\normalsize
\singlespacing
# \centering \onehalfspacing \Large \textsf{ \textcolor{teal}{Michael Long, PhD Candidate\vspace{-1em}}}
## \centering \large  _\textsf{\textcolor{teal}{Cognitive Scientist}}_
 
\centerline {904-557-1044}\centerline {
emlongsciences@gmail.com}\centerline {
github.com/emlongsciences}\centerline {
(R Markdown version of resumé available on github)\vspace{-.5em}}

# \Large \textsf{\textcolor{teal}{Objective\vspace{-1em}}}
Seeking the position of Research Scientist combining my expertise in methodologies & data modeling with my skills in leadership and communication\vspace{-2em}

# \Large \textsf{\textcolor{teal}{Highlights/Skills\vspace{-1em}}}
-   Lead Research Scientist -- Managed several research projects from identifying research goals and designing suitable plan to overseeing team of research assistants on data collection to communicating findings to stakeholders and fellow researchers
-   Senior Data Scientist -- Specialization in mixed-effects models and classification in machine learning; led the planning and execution of statistical analyses on large projects; consulted on various projects and taught data analysis course in *R*
-   Experimental Design and Methodologies -- behavioral measures, corpus studies, surveys, Machine Learning, Natural Language Processing
-   Programming Expertise -- _R_, _Python_, _MATLAB_, _SPSS_, _E-Prime_, _PsyToolkit_, _Qualtrics_\vspace{-2em}

# \Large \textsf{\textcolor{teal}{Education\vspace{-1em}}}
## \textsf {\normalsize \textbf Doctor of Philosophy, Cognition and Cognitive Neuroscience -- 2024\vspace{-1em}}
-   Florida State University
-   Posted graduation date: August, 2024\vspace{-2em}

## \textsf {\normalsize \textbf Master of Science, Experimental Psychology -- 2019\vspace{-1em}}
-   Nova Southeastern University\vspace{-2em}

## \textsf {\normalsize \textbf Bachelor of Arts, Psychology -- 2013\vspace{-1em}}
-   Florida Atlantic University\vspace{-2em}

# \Large \textsf {\textcolor{teal}{Experience}\vspace{-1em}}
## \textsf {\large \textbf Lead Research Scientist\vspace{-1em}}
### \textsf {\normalsize Learning, Memory, and Language Lab -- 2021-current\vspace{-1em}}
-   Managed several research projects examining language production and other cognitive processes using behavioral measures classifier models
-   Examined decision-making process in language production by testing relationship between spatial language and motor-action planning
-   Explored biological scaling (allometry) and its impact on memory and behavior
-   Consulted on Experimental Philosophy project about intentionality and actions
-   Transformed assessment of syntactic priming by redesigning paradigm to model natural discourse\vspace{-2em}

## \textsf {\large \textbf Senior Data Scientist\vspace{-1em}}
### \textsf {\normalsize \textbf Numerous projects in Cognitive Psychology; Linguistics; Philosophy\vspace{-1em}}
-   Managed small and large data sets 
-   Used several analytical approaches to answer various research questions
-   Communicated findings to diverse audiences through interpretation and translation of statistical results
-   Expertise in predictive statistical methods including Mixed-Effects Regression Modeling and Bayesian statistics
-   Knowledge of machine learning through use of MVPA in fMRI course
-   Knowledge of NLP, LLM, GPT from Python for Linguistics courses\vspace{-2em}

## \textsf {\large \textbf Leadership Experience\vspace{-1em}}
### \textsf {\normalsize \textbf Learning, Memory, and Language Lab (2019-current)\vspace{-1em}}
-   Trained and managed team of research assistants on several projects of experimental research with human subjects
-   Trained research assistants on programming and data analysis\vspace{-2em}

### \textsf {\normalsize \textbf Conditioning and Learning Lab Coordinator (2020-2021)\vspace{-1em}}
-   Trained and managed team of research assistants working on general care and operant conditioning training of rat specimens
-   Maintained lab space and lab equipment\vspace{-2em}

## \textsf {\large \textbf Teaching/Instruction Experience\vspace{-1em}}
### \textsf {\normalsize \textbf Lab Course Instructor\vspace{-1em}}
-   Cognitive Psychology (2023-)
-   Conditioning and Learning (2020-2023)\vspace{-2em}

### \textsf {\normalsize \textbf "sum(R) c('a','m','p')" -- Introduction to R for Psychological Research (2023)\vspace{-1em}}
-   Taught basics of *R* programming language with focus on data analysis, visualization, and presentation
-   Implemented program and developed custom curriculum



